services:

  postgres:
    image: postgres:16
    container_name: pizzaria-db
    environment:
      POSTGRES_DB: Pizzaria_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: pizzaria-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Pizzaria_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"